#!/usr/bin/env python3
"""Write src/ml/weights.ts from data/model/model.json (int8 dense, base64)."""
from __future__ import annotations

import argparse
import base64
import gzip
import hashlib
import json
from pathlib import Path

from common import MODEL_DIR, dump_json

ROOT = Path(__file__).resolve().parent.parent


def render(model: dict) -> str:
    raw = base64.b64decode(model["weights_q_b64"])
    assert len(raw) == model["buckets"], (len(raw), model["buckets"])
    t = model["thresholds"]
    return f"""// src/ml/weights.ts — GENERATED by training/export.py. Do not edit.
export const MODEL_META = {{
  version: '{model["version"]}',
  buckets: {model["buckets"]},
  storage: 'dense-int8',
  ngramChar: [{model["ngram_char"][0]}, {model["ngram_char"][1]}],
  ngramWord: [{model["ngram_word"][0]}, {model["ngram_word"][1]}],
  maxChars: {model["max_chars"]},
  scale: {model["scale"]!r},
  bias: {model["bias"]!r},
  norm: 'l2-binary', // logit = bias + scale * sumInt / sqrt(nnz)
  thresholds: {{ flag: {t["flag"]!r}, block: {t["block"]!r}, benign: {t["benign"]!r} }},
  trainedAt: '{model["trained_at"]}',
  sha256: '{hashlib.sha256(raw).hexdigest()}',
}} as const;
export const WEIGHTS_B64 =
  '{base64.b64encode(raw).decode()}';
"""


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--model", default=str(MODEL_DIR / "model.json"))
    ap.add_argument("--out", default=str(ROOT / "src" / "ml" / "weights.ts"))
    args = ap.parse_args()
    model = json.loads(Path(args.model).read_text())
    ts = render(model)
    out = Path(args.out)
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(ts)
    raw = base64.b64decode(model["weights_q_b64"])
    sizes = {"weights_ts_bytes": len(ts.encode()), "weights_ts_gz": len(gzip.compress(ts.encode(), 9)),
             "int8_raw": len(raw), "int8_gz": len(gzip.compress(raw, 9))}
    dump_json(MODEL_DIR / "export_sizes.json", sizes)
    print(f"wrote {out} — weights.ts {sizes['weights_ts_bytes']} B ({sizes['weights_ts_gz']} B gz); "
          f"int8 {sizes['int8_raw']} B ({sizes['int8_gz']} B gz)")


if __name__ == "__main__":
    main()
