import type { PatternRule } from '../types.js';

export const injectionRules: PatternRule[] = [
  {
    id: 'injection-ignore-previous',
    category: 'prompt-injection',
    pattern: /ignore\s+(all\s+)?(previous|prior|earlier|above|your)(\s+\w+)?\s+(instructions?|directives?|rules?|prompts?|context)/,
    weight: 10,
    precision: 'high',
    description: 'Ignore previous instructions',
  },
  {
    id: 'injection-disregard-above',
    category: 'prompt-injection',
    pattern: /disregard\s+(all\s+)?(the\s+)?(above|prior|previous|earlier|your)\s+(instructions?|directives?|rules?|context|text|prompt)/,
    weight: 9,
    precision: 'high',
    description: 'Disregard above/prior instructions',
  },
  {
    id: 'injection-forget-context',
    category: 'prompt-injection',
    pattern:
      /forget\s+(all\s+)?(your\s+)?(the\s+)?(previous|prior|earlier|above)\s+(instructions?|context|rules?|conversation|directives?)|forget\s+the\s+(instructions?|context|rules?|conversation|directives?)/,
    weight: 9,
    precision: 'high',
    description: 'Forget previous context/instructions',
  },
  {
    id: 'injection-forget-above',
    category: 'prompt-injection',
    // Short forms that omit the instruction noun: "Forget above.", "Forget everything."
    pattern: /forget\s+(all\s+(of\s+)?)?(the\s+)?(above|everything)\b|forget\s+all\s+(that|this)\b/,
    weight: 8,
    precision: 'high',
    description: 'Forget above/everything (short override)',
  },
  {
    id: 'injection-ignore-above-short',
    category: 'prompt-injection',
    pattern: /(ignore|disregard)\s+(all\s+)?(of\s+)?(the\s+)?above\b/,
    weight: 8,
    precision: 'medium',
    description: 'Ignore/disregard above (short override)',
  },
  {
    id: 'injection-discard-prior',
    category: 'prompt-injection',
    pattern: /(discard|drop|wipe|clear|reset)\s+(all\s+)?(the\s+)?(previous|prior|earlier|above)\s+(instructions?|context|rules?|memory|conversation|prompts?)/,
    weight: 7,
    precision: 'high',
    description: 'Discard/reset prior instructions or context',
  },
  {
    id: 'injection-new-instructions',
    category: 'prompt-injection',
    pattern: /(your|the)\s+(new|updated|actual|real|true|correct)\s+instructions?\s+(are|is|will\s+be)\s*:/,
    weight: 9,
    precision: 'high',
    description: 'Overriding with new instructions',
  },
  {
    id: 'injection-system-override',
    category: 'prompt-injection',
    pattern: /\[?\s*system\s*(prompt|message|instructions?)?\s*\]?\s*[:=]\s*/,
    weight: 8,
    precision: 'high',
    description: 'System prompt override marker',
  },
  {
    id: 'injection-override-directive',
    category: 'prompt-injection',
    pattern: /override\s+(the\s+)?(system|safety|initial|original|base)\s*(prompt|instructions?|directives?|rules?)?/,
    weight: 8,
    precision: 'high',
    description: 'Override system/safety directives',
  },
  {
    id: 'injection-special-tokens',
    category: 'prompt-injection',
    pattern: /(\[SYSTEM\]|\[INST\]|\[\/INST\]|<\|system\|>|<\|user\|>|<\|assistant\|>|<<SYS>>|<\/s>)/,
    weight: 9,
    precision: 'high',
    description: 'LLM special token injection',
  },
  {
    id: 'injection-xml-system',
    category: 'prompt-injection',
    pattern: /<\s*system\s*>|<\s*\/\s*system\s*>/,
    weight: 8,
    precision: 'high',
    description: 'XML system tag injection',
  },
  {
    id: 'injection-end-prompt-marker',
    category: 'prompt-injection',
    pattern: /---+\s*(end\s+of\s+)?(system\s+)?(prompt|instructions?)\s*---+/,
    weight: 8,
    precision: 'high',
    description: 'End-of-prompt delimiter injection',
  },
  {
    id: 'injection-real-task',
    category: 'prompt-injection',
    pattern: /your\s+(actual|real|true|correct)\s+(task|goal|purpose|objective|instructions?|mission)\s+(is|are|will\s+be)\b/,
    weight: 8,
    precision: 'high',
    description: "Redefining the model's real task",
  },
  {
    id: 'injection-context-switch',
    category: 'prompt-injection',
    pattern: /(now\s+)?switch\s+(to\s+)?context|context\s*switch\s*:/,
    weight: 6,
    precision: 'low',
    description: 'Context switching directive',
  },
  {
    id: 'injection-human-turn',
    category: 'prompt-injection',
    pattern: /<\/?(human|user|assistant|ai)\s*>|Human\s*:\s*\n|Assistant\s*:\s*\n/,
    weight: 7,
    precision: 'medium',
    description: 'Conversation turn injection',
  },
  {
    id: 'injection-chatml-im-tokens',
    category: 'prompt-injection',
    pattern: /<\|im_start\|>|<\|im_end\|>|<\|endoftext\|>|<\|end\|>|<\|start\|>/,
    weight: 9,
    precision: 'high',
    description: 'ChatML / im_start special token injection',
  },
  {
    id: 'injection-llama-header',
    category: 'prompt-injection',
    pattern: /<\|begin_of_text\|>|<\|start_header_id\|>|<\|end_header_id\|>|<\|eot_id\|>/,
    weight: 9,
    precision: 'high',
    description: 'Llama-style header/EOT token injection',
  },
  {
    id: 'injection-gemini-role',
    category: 'prompt-injection',
    pattern: /\b(system|model|user)\s*:\s*(you are|ignore|disregard|new instructions)/i,
    weight: 8,
    precision: 'high',
    description: 'Role-colon injection with override content',
  },
  {
    id: 'injection-fake-tool-call',
    category: 'prompt-injection',
    pattern: /["']?(tool_calls?|function_call|tool_use)["']?\s*:\s*\[?\s*\{/,
    weight: 8,
    precision: 'high',
    description: 'Fake tool/function call JSON injection',
  },
  {
    id: 'injection-policy-puppetry',
    category: 'prompt-injection',
    pattern: /(update|replace|set|override)\s+(the\s+)?(policy|policies|safety\s+policy|content\s+policy)\s*(to|with|:)/,
    weight: 9,
    precision: 'high',
    description: 'Policy puppetry — overwrite safety policy',
  },
  {
    id: 'injection-translate-then-obey',
    category: 'prompt-injection',
    pattern: /(translate|decode|decrypt|unscramble)\s+.{0,40}(then|and\s+then)\s+(follow|obey|execute|run|apply)\s+(the\s+)?(instructions?|commands?|directives?)/,
    weight: 8,
    precision: 'high',
    description: 'Translate/decode then obey wrapped instructions',
  },
  {
    id: 'injection-code-wrap',
    category: 'prompt-injection',
    pattern: /(in\s+(this|the)\s+(code|json|yaml|xml|markdown)\s*(block|snippet|payload)?|as\s+(json|yaml|xml))\s*[,:]?\s*.{0,40}(ignore|disregard|override|new\s+instructions?)/,
    weight: 7,
    precision: 'medium',
    description: 'Code/structured-payload wrapped injection',
  },
  {
    id: 'injection-process-last-prompt',
    category: 'prompt-injection',
    // "process/run/execute the last/previous prompt/message/request"
    pattern:
      /\b(process|run|execute|apply|perform|fulfill|continue|proceed)\s+(with\s+)?(my\s+|the\s+)?(last|previous|prior|earlier)\s+(prompt|message|request|instruction|query|command|question)\b/,
    weight: 6,
    precision: 'medium',
    description: 'Deferred execution of a prior prompt/message/request',
  },
  {
    id: 'injection-do-what-said-before',
    category: 'prompt-injection',
    // "do what I said before" / "answer what I asked in the previous message"
    pattern:
      /\b(do|answer|continue|complete|follow|execute|honou?r)\s+(with\s+)?(what|whatever)\s+i\s+(said|asked|requested|wrote)(\s+(before|earlier|previously|above)|\s+.{0,40}?\b(previous|prior|last|earlier)\s+(message|prompt|request|turn|question))\b/,
    weight: 6,
    precision: 'medium',
    description: 'Request to act on what the user said/asked in a prior turn',
  },
  {
    id: 'injection-retry-previous-request',
    category: 'prompt-injection',
    pattern:
      /\b(try\s+again|retry|re[\s-]?do|re[\s-]?run|re[\s-]?process)\s+(on\s+)?(my\s+|the\s+)?(previous|prior|last|earlier)\s+(request|prompt|message|instruction|query|command|question)\b/,
    weight: 6,
    precision: 'medium',
    description: 'Retry/re-do a previous request or prompt',
  },
];

/** Rule IDs that signal deferred reference to a prior turn (used by session correlation). */
export const DEFERRED_REFERENCE_RULE_IDS: ReadonlySet<string> = new Set([
  'injection-process-last-prompt',
  'injection-do-what-said-before',
  'injection-retry-previous-request',
]);
